// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koodawjkabqaezndneke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvb2Rhd2prYWJxYWV6bmRuZWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDE1OTYsImV4cCI6MjA3MzUxNzU5Nn0.2AUFUYjAF6NQ4a_ghlfTUcXtOip3ZccLLaBYTcODmbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});